version: '3.8'
services:
  cv-app:
    image: nginx:alpine
    container_name: cv-app
    restart: always
    volumes:
      - .:/usr/share/nginx/html:ro # הנקודה אומרת ל-Docker לקחת את קבצי הגיט
    networks:
      - openclaw_default

networks:
  openclaw_default:
    external: true
