version: '3'
services:
  cv-app:
    image: nginx:alpine
    container_name: cv-app
    restart: always
    volumes:
      - .:/usr/share/nginx/html # פקודה זו מחברת את קבצי הגיט לשרת
    networks:
      - openclaw_default

networks:
  openclaw_default:
    external: true
